Repository Spimy/Subtitles, pull requests merged in 2020-10, with the labels that each got.

#8 Add searching
  README.md
  package.json
  src/App.vue
  src/assets/Glasses.vue
  src/components/LangSelect.vue
  src/components/Load.vue
  src/components/Search.vue
  src/components/SearchResults.vue
  src/ts/media.ts
  src/views/Home.vue
  vue.config.js
Labels: enhancement, frontend

#7 Add unit tests
  tests/unit/.gitkeep
  tests/unit/lang-select.spec.js
Labels: documentation, enhancement

#9 Add movie subtitles page
  apps/v1/search/views.py
  public/index.html
  src/App.vue
  src/components/LangSelect.vue
  src/components/SearchResults.vue
  src/router/index.ts
  src/ts/media.ts
  src/views/Home.vue
  src/views/Movie.vue
  src/views/Show.vue
Labels: enhancement, frontend

#14 Fix images stretched horizontally in search results
  src/components/SearchResults.vue
Labels: frontend, improvement

#16 Break down lang select component
  src/components/LangSelect.vue
  src/components/LangSelect/Button.vue
  src/components/LangSelect/Index.vue
  src/components/LangSelect/Options.vue
  src/components/Search.vue
  src/views/Movie.vue
  tests/unit/LangSelect/Button.spec.js
  tests/unit/LangSelect/Options.spec.js
  tests/unit/lang-select.spec.js
Labels: documentation, frontend, improvement

#17 Add logo and hover highlight to poster less media
  src/assets/Logo.vue
  src/components/Image.vue
  src/components/SearchResults.vue
Labels: enhancement, frontend

#20 Refactor movie page into components
  src/components/Image.vue
  src/components/Media.vue
  src/components/Poster.vue
  src/components/SearchResults.vue
  src/components/Subtitles.vue
  src/main.ts
  src/ts/media.ts
  src/views/Movie.vue
Labels: frontend, improvement

#28 Update endpoints
  apps/v1/search/exceptions.py
  apps/v1/search/models.py
  apps/v1/search/tests/test_movie.py
  apps/v1/search/tests/test_show.py
  apps/v1/search/tests/test_subtitles.py
  apps/v1/search/urls.py
  apps/v1/search/views.py
  src/components/Search.vue
  src/components/SearchResults.vue
  src/ts/media.ts
  src/views/Home.vue
  src/views/Movie.vue
Labels: backend, frontend, improvement

#30 Add progressive web app
  Pipfile
  Pipfile.lock
  public/index.html
  public/offline.html
  public/static/icons/256.png
  public/static/splashscreens/1125x2436.png
  public/static/splashscreens/1242x2208.png
  public/static/splashscreens/1242x2688.png
  public/static/splashscreens/1536x2048.png
  public/static/splashscreens/1668x2224.png
  public/static/splashscreens/1668x2388.png
  public/static/splashscreens/2048x2732.png
  public/static/splashscreens/640x1136.png
  public/static/splashscreens/750x1334.png
  public/static/splashscreens/828x1792.png
  serviceworker.js
  src/components/SearchResults.vue
  src/views/Movie.vue
  subtitles/settings/base.py
  subtitles/urls.py
Labels: backend, enhancement, frontend

#31 Add robots app
  apps/robots/__init__.py
  apps/robots/apps.py
  apps/robots/migrations/__init__.py
  apps/robots/tests.py
  apps/robots/urls.py
  apps/robots/views.py
  subtitles/settings/base.py
  subtitles/urls.py
Labels: backend, improvement
